import { seedAirlineState } from '../../apps/headwinds-server/src/lib/worldService.mjs';
import { gameReducer } from '../../packages/engine/src/reducer.mjs';
const world = { id:'w', worldSeed:'s', currentYear: 5, currentWeek: 12, tickConfig: { startYear: 1950, startingCapital: 40_000_000 } };
let st = seedAirlineState(world, { airlineName: 'T', hub: 'LHR' });
st = gameReducer(st, { type:'ORDER_AIRCRAFT', typeId:'comet1', ownershipType:'owned', quantity:1 });
console.log('1954 W12 order comet:', st.pendingOrders.map(o=>[o.typeId,o.deliverAbsWeek]), 'error', st.error);
for (let i=0;i<8;i++) st = gameReducer(st, { type:'ADVANCE_WEEK', worldFuelIndex: 0.5, worldEvents: [], valuationNoise: 0 });
console.log('now', st.year, st.week, 'grounded', st.cometGrounded, 'fleet', st.fleet.map(a=>a.typeId), 'pending', st.pendingOrders.map(o=>[o.typeId,o.deliverAbsWeek]));
for (let i=0;i<20;i++) st = gameReducer(st, { type:'ADVANCE_WEEK', worldFuelIndex: 0.5, worldEvents: [], valuationNoise: 0 });
console.log('now', st.year, st.week, 'fleet', st.fleet.map(a=>a.typeId), 'pending', st.pendingOrders.length);
const st2 = gameReducer(st, { type:'ORDER_AIRCRAFT', typeId:'comet1', ownershipType:'lease' });
console.log('1954 W40 lease comet after grounding: pending', st2.pendingOrders.map(o=>o.typeId), 'error', st2.error);
const st3 = gameReducer(st, { type:'ORDER_AIRCRAFT', typeId:'comet1', quantity:1, ownershipType:'owned' });
console.log('toasts', (st3.pendingToasts??[]).map(t=>t.title+': '+t.message).slice(-2), 'cash', st.cash);
import { orderDenial } from '../../packages/engine/src/reducer.mjs';
console.log('denial', orderDenial(st, 'comet1'), 'cy', st.startYear, st.year);
console.log('AFTER GROUNDING order at 1954 W40 -> fleet', st3.fleet.map(a=>a.typeId+':'+a.status), 'grounded flag', st3.cometGrounded);
let st4 = st3; for (let i=0;i<14;i++) st4 = gameReducer(st4, { type:'ADVANCE_WEEK', worldFuelIndex: 0.5, worldEvents: [], valuationNoise: 0 });
console.log('1955 W2 fleet', st4.fleet.map(a=>a.typeId+':'+a.status));
