#!/usr/bin/env node
// tools/devlog-autolog.mjs
// -----------------------------------------------------------------------------
// Auto-maintains the "Full change history" feed in the Headwinds devlog.
//
//   node tools/devlog-autolog.mjs
//
// Every commit since SINCE (exclusive) becomes one .entry card (date + subject),
// newest first, inside an AUTO block delimited by the markers below. The
// hand-written "highlights" entries ABOVE the START marker are never touched.
//
// The block is regenerated wholesale from `git log` on every run, so the output
// is deterministic: run it twice with no new commits and the file is byte-for-
// byte identical (the post-commit hook relies on this to avoid empty commits).
//
// Only the commit SUBJECT is published — bodies often carry internal identifiers
// that don't belong on a public page.
//
// Skipped commits:
//   * merge commits             (--no-merges)
//   * "Sync from Tailwinds ..."  (engine changes are chronicled on the Tailwinds
//                                 devlog, per this page's own lede)
//   * "chore(devlog) ..."        (the hook's own bookkeeping commits)
//   * anything containing [skip devlog] in its subject or body
// -----------------------------------------------------------------------------
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HW     = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const DEVLOG = path.join(HW, 'apps', 'headwinds-web', 'pages', 'devlog.html');

// First commit AFTER which the auto-feed starts. 3bb6781 = "Headwinds site:
// landing page, app at /play, rebranded info pages + devlog" (site launch);
// everything before it is either pre-launch or covered by a curated highlight.
const SINCE = '3bb6781';

const START = '<!-- AUTO-DEVLOG:START — generated by tools/devlog-autolog.mjs; do not edit inside this block by hand -->';
const END   = '<!-- AUTO-DEVLOG:END -->';

const git = (args) => execFileSync('git', args, { cwd: HW, encoding: 'utf8' });

const RS = '\x1e', FS = '\x1f';
let raw = '';
try {
  raw = git(['log', '--no-merges', '--date=short',
    `--pretty=format:%H${FS}%ad${FS}%s${FS}%b${RS}`, `${SINCE}..HEAD`]);
} catch (err) {
  console.error(`devlog-autolog: could not read git log (${err.message}); skipping.`);
  process.exit(0);
}

const commits = raw.split(RS).map((s) => s.replace(/^\n+/, '')).filter((s) => s.trim())
  .map((rec) => {
    const [hash = '', date = '', subject = '', body = ''] = rec.split(FS);
    return { hash: hash.trim(), date: date.trim(), subject: subject.trim(), body };
  });

const MONTHS = ['January','February','March','April','May','June','July',
  'August','September','October','November','December'];
const humanDate = (iso) => {
  const [y, m, d] = iso.split('-').map(Number);
  return `${MONTHS[m - 1]} ${d}, ${y}`;
};
const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const keep = commits.filter((c) =>
  c.hash &&
  !/^Sync from Tailwinds/i.test(c.subject) &&
  !/^chore\(devlog\)/i.test(c.subject) &&
  !/\[skip devlog\]/i.test(`${c.subject}\n${c.body}`)
);

const cards = keep.map((c) =>
  `      <div class="entry" data-commit="${c.hash.slice(0, 7)}">
        <p class="date">${humanDate(c.date)}</p>
        <h3 style="margin-top:0">${esc(c.subject)}</h3>
      </div>`).join('\n');

const block = `${START}
      <h2 style="margin-top:44px">Full change history</h2>
      <p class="lede" style="font-size:0.98rem; margin-bottom:20px;">Every change that ships to Headwinds, newest first — generated automatically from the commit history. The highlights above are the hand-written story; this is the complete record.</p>
${cards}
      ${END}`;

let html = readFileSync(DEVLOG, 'utf8');
const rx = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const between = new RegExp(rx(START) + '[\\s\\S]*?' + rx(END));

if (between.test(html)) {
  html = html.replace(between, block);
} else if (html.includes('</main>')) {
  html = html.replace('</main>', `${block}\n  </main>`);
} else {
  console.error('devlog-autolog: no </main> and no existing markers found; leaving file untouched.');
  process.exit(1);
}

writeFileSync(DEVLOG, html);
console.log(`devlog-autolog: wrote ${keep.length} change-history entr${keep.length === 1 ? 'y' : 'ies'}.`);
